services:
  - type: web
    name: chatapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT run:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chatapp-db
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: REMEMBER_COOKIE_SECURE
        value: true

  - type: pserv
    name: chatapp-db
    databaseName: chatapp
    plan: free
